// loading
export const SET_LOADING = "SET_LOADING";

// MemberActions
export const SAVE_ALL_MEMBERS = "SAVE_ALL_MEMBERS"
export const MEMBER_ADDED = "MEMBER_ADDED"
export const MEMBER_DELETED = "MEMBER_DELETED"
export const MEMBER_UPDATED = "MEMBER_UPDATED"
export const ACTIVE_MEMBER_CHANGED = "ACTIVE_MEMBER_CHANGED"

// VaccinationActions
export const SAVE_ALL_VACCINATIONS = "SAVE_ALL_VACCINATIONS"
export const VACCINATION_ADDED = "VACCINATION_ADDED"
export const VACCINATION_DELETED = "VACCINATION_DELETED"
export const VACCINATION_UPDATED = "VACCINATION_UPDATED"

// CoronaPatientActions
export const SAVE_ALL_PATIENTS = "SAVE_ALL_PATIENTS"
export const SAVE_PATIENT = "SAVE_PATIENT"
export const PATIENT_ADDED = "PATIENT_ADDED"
export const PATIENT_DELETED = "PATIENT_DELETED"
export const PATIENT_UPDATED = "PATIENT_UPDATED"

// Cities
export const SAVE_ALL_CITIES = "SAVE_ALL_CITIES"




